/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EquilibrioRouteImport } from './routes/equilibrio'
import { Route as ComparadorRouteImport } from './routes/comparador'
import { Route as ComparacaoRouteImport } from './routes/comparacao'
import { Route as IndexRouteImport } from './routes/index'

const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EquilibrioRoute = EquilibrioRouteImport.update({
  id: '/equilibrio',
  path: '/equilibrio',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparadorRoute = ComparadorRouteImport.update({
  id: '/comparador',
  path: '/comparador',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparacaoRoute = ComparacaoRouteImport.update({
  id: '/comparacao',
  path: '/comparacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comparacao': typeof ComparacaoRoute
  '/comparador': typeof ComparadorRoute
  '/equilibrio': typeof EquilibrioRoute
  '/financeiro': typeof FinanceiroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comparacao': typeof ComparacaoRoute
  '/comparador': typeof ComparadorRoute
  '/equilibrio': typeof EquilibrioRoute
  '/financeiro': typeof FinanceiroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comparacao': typeof ComparacaoRoute
  '/comparador': typeof ComparadorRoute
  '/equilibrio': typeof EquilibrioRoute
  '/financeiro': typeof FinanceiroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/comparacao' | '/comparador' | '/equilibrio' | '/financeiro'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/comparacao' | '/comparador' | '/equilibrio' | '/financeiro'
  id:
    | '__root__'
    | '/'
    | '/comparacao'
    | '/comparador'
    | '/equilibrio'
    | '/financeiro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComparacaoRoute: typeof ComparacaoRoute
  ComparadorRoute: typeof ComparadorRoute
  EquilibrioRoute: typeof EquilibrioRoute
  FinanceiroRoute: typeof FinanceiroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equilibrio': {
      id: '/equilibrio'
      path: '/equilibrio'
      fullPath: '/equilibrio'
      preLoaderRoute: typeof EquilibrioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparador': {
      id: '/comparador'
      path: '/comparador'
      fullPath: '/comparador'
      preLoaderRoute: typeof ComparadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparacao': {
      id: '/comparacao'
      path: '/comparacao'
      fullPath: '/comparacao'
      preLoaderRoute: typeof ComparacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComparacaoRoute: ComparacaoRoute,
  ComparadorRoute: ComparadorRoute,
  EquilibrioRoute: EquilibrioRoute,
  FinanceiroRoute: FinanceiroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
